from flask import Flask, jsonify
from fastpitch_scraper import run_all_scrapers
import json
import os

app = Flask(__name__)

DATA_FILE = "fastpitch_master.json"


def get_events():
    """
    Reads the JSON file generated by run_all_scrapers().
    Returns empty structure if file doesn't exist yet.
    """
    if not os.path.exists(DATA_FILE):
        return {"count": 0, "events": []}

    with open(DATA_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


@app.route("/")
def home():
    return "Fastpitch Scraper is running!"


@app.route("/events")
def events():
    return jsonify(get_events())


# -------- RUN SCRAPERS ON STARTUP --------
# Runs once when Render boots the service
run_all_scrapers()


if __name__ == "__main__":
    # Render uses PORT env variable
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port)

